sudo: true
os: trusty
cache: false
env:
- SFDX_URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  CONSUMER_KEY=3MVG9G9pzCUSkzZudlqnkY3TyOCSNo.sfmm9RzEpa7nnlp3mQRSZuNlSXa8qhGy4rApe1aSknefjqHviFnCSa
  USERNAME=engineering@propic.com.au
before_install:
- openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv
  -in .travis/server.key.enc -out .travis/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $SFDX_URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile .travis/server.key
  --username $USERNAME -a HubOrg
script:
- sfdx force:org:create -v HubOrg -f config/project-scratch-def.json -a CiOrg --wait
  20
- sfdx force:org:display -u CiOrg
- sfdx force:mdapi:deploy -u CiOrg -d src -w 100
- sfdx force:apex:test:run -u CiOrg -w 100
- sfdx force:org:delete -u CiOrg -p
